== HOME TASK
As a basis for this home task, use this git repository: https://github.com/vitalliuss/helloci

1. Jenkins Installation:
    * Install Jenkins server on local or remote machine;
    * Change Jenkins default port to 8081;
    * Create slave node on remote or local machine (you may use the same (one) machine for master and slave);
2. Job configuration:
   * Job 1:
     * Get code from git repository: https://github.com/vitalliuss/helloci
     * build application from Java folder with Maven
   * Job 2:
     * Pull code of your framework (you created in previous tasks).
     * Run test you created.
     * Add parametrization of your job (browser, test suite, environment, etc.).
   * Set job triggers:
     * After commit in VCS no longer than in 5 minutes
     * At midnight every day
     * Job should run on slave only

3. As the result share the link to Jenkins OR set of detailed screenshots of Jenkins and job configuration & logs with your mentor.

=== ACCEPTANCE CRITERIA
1.	Jenkins server has been set up on local or remote machine with default port 8081
2.	Slave node has been created
3.	Jobs has been configured with necessary settings, parameters and build actions
4.	Job is triggered according to task
5.	Job has been set up to run on slave node only

=== BONUS TASK
1.	Make server on linux (use Cloud or virtual machine)
2.	Make node on linux
3.	Configure job history tracking and server backup
