### Successful test: check response status is 200
GET https://jsonplaceholder.typicode.com/users

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
